//landcodes for autocomplete of Source Country entry
countryCodes = [
{code:'AF',name:'AFGHANISTAN'},
{code:'AX',name:'ÅLAND ISLANDS'},
{code:'AL',name:'ALBANIA'},
{code:'DZ',name:'ALGERIA'},
{code:'AS',name:'AMERICAN SAMOA'},
{code:'AD',name:'ANDORRA'},
{code:'AO',name:'ANGOLA'},
{code:'AI',name:'ANGUILLA'},
{code:'AQ',name:'ANTARCTICA'},
{code:'AG',name:'ANTIGUA AND BARBUDA'},
{code:'AR',name:'ARGENTINA'},
{code:'AM',name:'ARMENIA'},
{code:'AW',name:'ARUBA'},
{code:'AU',name:'AUSTRALIA'},
{code:'AT',name:'AUSTRIA'},
{code:'AZ',name:'AZERBAIJAN'},
{code:'BS',name:'BAHAMAS'},
{code:'BH',name:'BAHRAIN'},
{code:'BD',name:'BANGLADESH'},
{code:'BB',name:'BARBADOS'},
{code:'BY',name:'BELARUS'},
{code:'BE',name:'BELGIUM'},
{code:'BZ',name:'BELIZE'},
{code:'BJ',name:'BENIN'},
{code:'BM',name:'BERMUDA'},
{code:'BT',name:'BHUTAN'},
{code:'BO',name:'BOLIVIA, PLURINATIONAL STATE OF'},
{code:'BQ',name:'BONAIRE, SINT EUSTATIUS AND SABA'},
{code:'BA',name:'BOSNIA AND HERZEGOVINA'},
{code:'BW',name:'BOTSWANA'},
{code:'BV',name:'BOUVET ISLAND'},
{code:'BR',name:'BRAZIL'},
{code:'IO',name:'BRITISH INDIAN OCEAN TERRITORY'},
{code:'BN',name:'BRUNEI DARUSSALAM'},
{code:'BG',name:'BULGARIA'},
{code:'BF',name:'BURKINA FASO'},
{code:'BI',name:'BURUNDI'},
{code:'KH',name:'CAMBODIA'},
{code:'CM',name:'CAMEROON'},
{code:'CA',name:'CANADA'},
{code:'CV',name:'CAPE VERDE'},
{code:'KY',name:'CAYMAN ISLANDS'},
{code:'CF',name:'CENTRAL AFRICAN REPUBLIC'},
{code:'TD',name:'CHAD'},
{code:'CL',name:'CHILE'},
{code:'CN',name:'CHINA'},
{code:'CX',name:'CHRISTMAS ISLAND'},
{code:'CC',name:'COCOS (KEELING) ISLANDS'},
{code:'CO',name:'COLOMBIA'},
{code:'KM',name:'COMOROS'},
{code:'CG',name:'CONGO'},
{code:'CD',name:'CONGO, THE DEMOCRATIC REPUBLIC OF THE'},
{code:'CK',name:'COOK ISLANDS'},
{code:'CR',name:'COSTA RICA'},
{code:'CI',name:'CÔTE D IVOIRE'},
{code:'HR',name:'CROATIA'},
{code:'CU',name:'CUBA'},
{code:'CW',name:'CURAÇAO'},
{code:'CY',name:'CYPRUS'},
{code:'CZ',name:'CZECH REPUBLIC'},
{code:'DK',name:'DENMARK'},
{code:'DJ',name:'DJIBOUTI'},
{code:'DM',name:'DOMINICA'}];

/*
DO	DOMINICAN REPUBLIC
EC	ECUADOR
EG	EGYPT
SV	EL SALVADOR
GQ	EQUATORIAL GUINEA
ER	ERITREA
EE	ESTONIA
ET	ETHIOPIA
FK	FALKLAND ISLANDS (MALVINAS)
FO	FAROE ISLANDS
FJ	FIJI
FI	FINLAND
FR	FRANCE
GF	FRENCH GUIANA
PF	FRENCH POLYNESIA
TF	FRENCH SOUTHERN TERRITORIES
GA	GABON
GM	GAMBIA
GE	GEORGIA
DE	GERMANY
GH	GHANA
GI	GIBRALTAR
GR	GREECE
GL	GREENLAND
GD	GRENADA
GP	GUADELOUPE
GU	GUAM
GT	GUATEMALA
GG	GUERNSEY
GN	GUINEA
GW	GUINEA-BISSAU
GY	GUYANA
HT	HAITI
HM	HEARD ISLAND AND MCDONALD ISLANDS
VA	HOLY SEE (VATICAN CITY STATE)
HN	HONDURAS
HK	HONG KONG
HU	HUNGARY
IS	ICELAND
IN	INDIA
ID	INDONESIA
IR	IRAN, ISLAMIC REPUBLIC OF
IQ	IRAQ
IE	IRELAND
IM	ISLE OF MAN
IL	ISRAEL
IT	ITALY
JM	JAMAICA
JP	JAPAN
JE	JERSEY
JO	JORDAN
KZ	KAZAKHSTAN
KE	KENYA
KI	KIRIBATI
KP	KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF
KR	KOREA, REPUBLIC OF
KW	KUWAIT
KG	KYRGYZSTAN
LA	LAO PEOPLE'S DEMOCRATIC REPUBLIC
LV	LATVIA
LB	LEBANON
LS	LESOTHO
LR	LIBERIA
LY	LIBYA
LI	LIECHTENSTEIN
LT	LITHUANIA
LU	LUXEMBOURG
MO	MACAO
MK	MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF
MG	MADAGASCAR
MW	MALAWI
MY	MALAYSIA
MV	MALDIVES
ML	MALI
MT	MALTA
MH	MARSHALL ISLANDS
MQ	MARTINIQUE
MR	MAURITANIA
MU	MAURITIUS
YT	MAYOTTE
MX	MEXICO
FM	MICRONESIA, FEDERATED STATES OF
MD	MOLDOVA, REPUBLIC OF
MC	MONACO
MN	MONGOLIA
ME	MONTENEGRO
MS	MONTSERRAT
MA	MOROCCO
MZ	MOZAMBIQUE
MM	MYANMAR
NA	NAMIBIA
NR	NAURU
NP	NEPAL
NL	NETHERLANDS
NC	NEW CALEDONIA
NZ	NEW ZEALAND
NI	NICARAGUA
NE	NIGER
NG	NIGERIA
NU	NIUE
NF	NORFOLK ISLAND
MP	NORTHERN MARIANA ISLANDS
NO	NORWAY
OM	OMAN
PK	PAKISTAN
PW	PALAU
PS	PALESTINE, STATE OF
PA	PANAMA
PG	PAPUA NEW GUINEA
PY	PARAGUAY
PE	PERU
PH	PHILIPPINES
PN	PITCAIRN
PL	POLAND
PT	PORTUGAL
PR	PUERTO RICO
QA	QATAR
RE	RÉUNION
RO	ROMANIA
RU	RUSSIAN FEDERATION
RW	RWANDA
BL	SAINT BARTHÉLEMY
SH	SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA
KN	SAINT KITTS AND NEVIS
LC	SAINT LUCIA
MF	SAINT MARTIN (FRENCH PART)
PM	SAINT PIERRE AND MIQUELON
VC	SAINT VINCENT AND THE GRENADINES
WS	SAMOA
SM	SAN MARINO
ST	SAO TOME AND PRINCIPE
SA	SAUDI ARABIA
SN	SENEGAL
RS	SERBIA
SC	SEYCHELLES
SL	SIERRA LEONE
SG	SINGAPORE
SX	SINT MAARTEN (DUTCH PART)
SK	SLOVAKIA
SI	SLOVENIA
SB	SOLOMON ISLANDS
SO	SOMALIA
ZA	SOUTH AFRICA
GS	SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS
SS	SOUTH SUDAN
ES	SPAIN
LK	SRI LANKA
SD	SUDAN
SR	SURINAME
SJ	SVALBARD AND JAN MAYEN
SZ	SWAZILAND
SE	SWEDEN
CH	SWITZERLAND
SY	SYRIAN ARAB REPUBLIC
TW	TAIWAN, PROVINCE OF CHINA
TJ	TAJIKISTAN
TZ	TANZANIA, UNITED REPUBLIC OF
TH	THAILAND
TL	TIMOR-LESTE
TG	TOGO
TK	TOKELAU
TO	TONGA
TT	TRINIDAD AND TOBAGO
TN	TUNISIA
TR	TURKEY
TM	TURKMENISTAN
TC	TURKS AND CAICOS ISLANDS
TV	TUVALU
UG	UGANDA
UA	UKRAINE
AE	UNITED ARAB EMIRATES
GB	UNITED KINGDOM
US	UNITED STATES
UM	UNITED STATES MINOR OUTLYING ISLANDS
UY	URUGUAY
UZ	UZBEKISTAN
VU	VANUATU
VE	VENEZUELA, BOLIVARIAN REPUBLIC OF
VN	VIET NAM
VG	VIRGIN ISLANDS, BRITISH
VI	VIRGIN ISLANDS, U.S.
WF	WALLIS AND FUTUNA
EH	WESTERN SAHARA
YE	YEMEN
ZM	ZAMBIA
ZW	ZIMBABWE
*/